config/routes.rb
Rails.application.routes.draw do
  get 'web_service/webservice'
    get 'web_service/online'

  resources :transactions
  resources :tags
  

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:codicetelecomando, :nome, :cognome, :seggnatario, :data, :serial_number, :internal_sn, :data_setup_agg_firmware, :data_attivazione, :data_disattivazione, :stato, :data_sostituzione, :sostituto_da, :note)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    
    @tags=Tag.where("id<?",100000000000)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @tags=Tags.where("id<?",10000000000)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:data, :ora, :direzione, :codice_utente, :controlli, :esito, :sorgente, :edizione, :varco, :tracciato_tessera, :slave_id, :lettore, :tipo, :fullcode, :term_id, :mac, :localip, :dhcp, :date, :time, :localtransaction, :io, :iox, :gate_state, :gate_state_ex, :slave_state_ex, :batt, :batt_mv)
    end
end

app/controllers/web_service_controller.rb
class WebServiceController < ApplicationController
  def webservice
    @transaction = Transaction.new
    params.each do |key,value|
      Rails.logger.warn "Param #{key}: #{value}"
      if key=="tr_data"
        @transaction.data=value.split(",")[0]
        @transaction.ora=value.split(",")[1]
        @transaction.direzione=value.split(",")[2]
        @transaction.codice_utente=value.split(",")[4]
        @transaction.controlli=value.split(",")[5]
        @transaction.esito=value.split(",")[6]
        @transaction.sorgente=value.split(",")[7]
        @transaction.edizione=value.split(",")[8]
        @transaction.varco=value.split(",")[9]
        @transaction.tracciato_tessera=value.split(",")[10]
        @transaction.slave_id=value.split(",")[11]
        @transaction.lettore=value.split(",")[12]
        @transaction.tipo=value.split(",")[13]
      end
      if key=="fullcode"
        @transaction.fullcode=value
      end 
      if key=="term_id"
        @transaction.term_id=value
      end
      if key=="mac"
        @transaction.mac=value
      end
      if key=="localip"
        @transaction.localip=value
      end
      if key=="dhcp"
        @transaction.dhcp=value
      end
      if key=="date"
        @transaction.date=value
      end
      if key=="time"
        @transaction.time=value
      end
      if key=="localtransaction"
        @transaction.localtransaction=value
      end
      if key=="io"
        @transaction.io=value
      end
      if key=="iox"
        @transaction.iox=value
      end
      if key=="gate_state"
        @transaction.gate_state=value
      end
      if key=="gate_state_ex"
        @transaction.gate_state_ex=value
      end
      if key=="slave_state_ex"
        @transaction.slave_state_ex=value
      end
      if key=="batt"
        @transaction.batt=value
      end   
      if key=="batt_mv"
        @transaction.batt_mv=value
      end
      
    end
    if @transaction.save
      respond_to do |format| 
         format.html { render  plain: "save=0\nack=1" }
      end
    else
      respond_to do |format|
         format.html { render plain: "save=1 \n" }
      end
    end
  end
  def online
     respond_to do |format|
         format.html { render plain: "save=1 \ntrnsaction=1 " }
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/web_service_helper.rb
module WebServiceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="tags">Tags</a></li>
          <li><a href="/transactions">Transactions</a></li>
       
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codicetelecomando %><br>
    <%= f.text_field :codicetelecomando %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cognome %><br>
    <%= f.text_field :cognome %>
  </div>
  <div class="field">
    <%= f.label :seggnatario %><br>
    <%= f.text_field :seggnatario %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br>
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :internal_sn %><br>
    <%= f.text_field :internal_sn %>
  </div>
  <div class="field">
    <%= f.label :data_setup_agg_firmware %><br>
    <%= f.datetime_select :data_setup_agg_firmware %>
  </div>
  <div class="field">
    <%= f.label :data_attivazione %><br>
    <%= f.datetime_select :data_attivazione %>
  </div>
  <div class="field">
    <%= f.label :data_disattivazione %><br>
    <%= f.datetime_select :data_disattivazione %>
  </div>
  <div class="field">
    <%= f.label :stato %><br>
    <%= f.text_field :stato %>
  </div>
  <div class="field">
    <%= f.label :data_sostituzione %><br>
    <%= f.datetime_select :data_sostituzione %>
  </div>
  <div class="field">
    <%= f.label :sostituto_da %><br>
    <%= f.text_field :sostituto_da %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Codicetelecomando</th>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Seggnatario</th>
      <th>Data</th>
      <th>Serial number</th>
      <th>Internal sn</th>
      <th>Data setup agg firmware</th>
      <th>Data attivazione</th>
      <th>Data disattivazione</th>
      <th>Stato</th>
      <th>Data sostituzione</th>
      <th>Sostituto da</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.codicetelecomando %></td>
        <td><%= tag.nome %></td>
        <td><%= tag.cognome %></td>
        <td><%= tag.seggnatario %></td>
        <td><%= tag.data %></td>
        <td><%= tag.serial_number %></td>
        <td><%= tag.internal_sn %></td>
        <td><%= tag.data_setup_agg_firmware %></td>
        <td><%= tag.data_attivazione %></td>
        <td><%= tag.data_disattivazione %></td>
        <td><%= tag.stato %></td>
        <td><%= tag.data_sostituzione %></td>
        <td><%= tag.sostituto_da %></td>
        <td><%= tag.note %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codicetelecomando:</strong>
  <%= @tag.codicetelecomando %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @tag.nome %>
</p>

<p>
  <strong>Cognome:</strong>
  <%= @tag.cognome %>
</p>

<p>
  <strong>Seggnatario:</strong>
  <%= @tag.seggnatario %>
</p>

<p>
  <strong>Data:</strong>
  <%= @tag.data %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @tag.serial_number %>
</p>

<p>
  <strong>Internal sn:</strong>
  <%= @tag.internal_sn %>
</p>

<p>
  <strong>Data setup agg firmware:</strong>
  <%= @tag.data_setup_agg_firmware %>
</p>

<p>
  <strong>Data attivazione:</strong>
  <%= @tag.data_attivazione %>
</p>

<p>
  <strong>Data disattivazione:</strong>
  <%= @tag.data_disattivazione %>
</p>

<p>
  <strong>Stato:</strong>
  <%= @tag.stato %>
</p>

<p>
  <strong>Data sostituzione:</strong>
  <%= @tag.data_sostituzione %>
</p>

<p>
  <strong>Sostituto da:</strong>
  <%= @tag.sostituto_da %>
</p>

<p>
  <strong>Note:</strong>
  <%= @tag.note %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :ora %><br>
    <%= f.text_field :ora %>
  </div>
  <div class="field">
    <%= f.label :direzione %><br>
    <%= f.text_field :direzione %>
  </div>
  <div class="field">
    <%= f.label :codice_utente %><br>
    <%= f.text_field :codice_utente %>
  </div>
  <div class="field">
    <%= f.label :controlli %><br>
    <%= f.text_field :controlli %>
  </div>
  <div class="field">
    <%= f.label :esito %><br>
    <%= f.text_field :esito %>
  </div>
  <div class="field">
    <%= f.label :sorgente %><br>
    <%= f.text_field :sorgente %>
  </div>
  <div class="field">
    <%= f.label :edizione %><br>
    <%= f.text_field :edizione %>
  </div>
  <div class="field">
    <%= f.label :varco %><br>
    <%= f.text_field :varco %>
  </div>
  <div class="field">
    <%= f.label :tracciato_tessera %><br>
    <%= f.text_field :tracciato_tessera %>
  </div>
  <div class="field">
    <%= f.label :slave_id %><br>
    <%= f.text_field :slave_id %>
  </div>
  <div class="field">
    <%= f.label :lettore %><br>
    <%= f.text_field :lettore %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :fullcode %><br>
    <%= f.text_area :fullcode %>
  </div>
  <div class="field">
    <%= f.label :term_id %><br>
    <%= f.text_field :term_id %>
  </div>
  <div class="field">
    <%= f.label :mac %><br>
    <%= f.text_field :mac %>
  </div>
  <div class="field">
    <%= f.label :localip %><br>
    <%= f.text_field :localip %>
  </div>
  <div class="field">
    <%= f.label :dhcp %><br>
    <%= f.text_field :dhcp %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :localtransaction %><br>
    <%= f.text_field :localtransaction %>
  </div>
  <div class="field">
    <%= f.label :io %><br>
    <%= f.text_field :io %>
  </div>
  <div class="field">
    <%= f.label :iox %><br>
    <%= f.text_field :iox %>
  </div>
  <div class="field">
    <%= f.label :gate_state %><br>
    <%= f.text_field :gate_state %>
  </div>
  <div class="field">
    <%= f.label :gate_state_ex %><br>
    <%= f.text_field :gate_state_ex %>
  </div>
  <div class="field">
    <%= f.label :slave_state_ex %><br>
    <%= f.text_field :slave_state_ex %>
  </div>
  <div class="field">
    <%= f.label :batt %><br>
    <%= f.text_field :batt %>
  </div>
  <div class="field">
    <%= f.label :batt_mv %><br>
    <%= f.text_field :batt_mv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table class="table" id="table">
  <thead>
    <tr>
      <th>Data-Ora</th>
      <th>Codice utente</th>
      <th>Controlli</th>
      <th>Esito</th>
      <th>Sorgente</th>
      <th>Edizione</th>
      <th>Varco</th>
      <th>Lettore</th>
      <th>Term</th>
      <th>Mac</th>
      <th ></th>     <th ></th>     <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.data[6] %><%= transaction.data[7] %>/<%= transaction.data[4] %><%= transaction.data[5] %>/<%= transaction.data[0] %><%= transaction.data[1] %><%= transaction.data[2] %><%= transaction.data[3] %> - <%= transaction.ora[0] %><%= transaction.ora[1] %>:<%= transaction.ora[2] %><%= transaction.ora[3] %>:<%= transaction.ora[4] %><%= transaction.ora[5] %></td>
        <td><%= @tags.where(" internal_sn= #{transaction.codice_utente}" ).first.codicetelecomando %></td>
        <td><%= transaction.controlli %></td>
        <td><%= transaction.esito %></td>
        <td><%= transaction.sorgente %></td>
        <td><%= transaction.edizione %></td>
        <td><%= transaction.varco %></td>
        <td><%= transaction.lettore %></td>
        <td><%= transaction.term_id %></td>
        <td><%= transaction.mac %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>
<script>
  $('#table').DataTable({

});
</script>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @transaction.data %>
</p>

<p>
  <strong>Ora:</strong>
  <%= @transaction.ora %>
</p>

<p>
  <strong>Direzione:</strong>
  <%= @transaction.direzione %>
</p>

<p>
  <strong>Codice utente:</strong>
  <%= @transaction.codice_utente %>
</p>

<p>
  <strong>Controlli:</strong>
  <%= @transaction.controlli %>
</p>

<p>
  <strong>Esito:</strong>
  <%= @transaction.esito %>
</p>

<p>
  <strong>Sorgente:</strong>
  <%= @transaction.sorgente %>
</p>

<p>
  <strong>Edizione:</strong>
  <%= @transaction.edizione %>
</p>

<p>
  <strong>Varco:</strong>
  <%= @transaction.varco %>
</p>

<p>
  <strong>Tracciato tessera:</strong>
  <%= @transaction.tracciato_tessera %>
</p>

<p>
  <strong>Slave:</strong>
  <%= @transaction.slave_id %>
</p>

<p>
  <strong>Lettore:</strong>
  <%= @transaction.lettore %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @transaction.tipo %>
</p>

<p>
  <strong>Fullcode:</strong>
  <%= @transaction.fullcode %>
</p>

<p>
  <strong>Term:</strong>
  <%= @transaction.term_id %>
</p>

<p>
  <strong>Mac:</strong>
  <%= @transaction.mac %>
</p>

<p>
  <strong>Localip:</strong>
  <%= @transaction.localip %>
</p>

<p>
  <strong>Dhcp:</strong>
  <%= @transaction.dhcp %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @transaction.time %>
</p>

<p>
  <strong>Localtransaction:</strong>
  <%= @transaction.localtransaction %>
</p>

<p>
  <strong>Io:</strong>
  <%= @transaction.io %>
</p>

<p>
  <strong>Iox:</strong>
  <%= @transaction.iox %>
</p>

<p>
  <strong>Gate state:</strong>
  <%= @transaction.gate_state %>
</p>

<p>
  <strong>Gate state ex:</strong>
  <%= @transaction.gate_state_ex %>
</p>

<p>
  <strong>Slave state ex:</strong>
  <%= @transaction.slave_state_ex %>
</p>

<p>
  <strong>Batt:</strong>
  <%= @transaction.batt %>
</p>

<p>
  <strong>Batt mv:</strong>
  <%= @transaction.batt_mv %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/web_service/webservice.html.erb
ack=1
save=1